flip:
  description: Toggles the mattress side and updates the flip date.
  fields:
    device_id:
      name: Device
      description: The mattress device you want to flip.
      required: true
      selector:
        device:
          integration: mattress_tracker
    date:
      name: Date
      description: The date the flip occurred (defaults to today).
      selector:
        date:

rotate:
  description: Toggles the mattress rotation and updates the rotation date.
  fields:
    device_id:
      name: Device
      description: The mattress device you want to rotate.
      required: true
      selector:
        device:
          integration: mattress_tracker
    date:
      name: Date
      description: The date the rotation occurred (defaults to today).
      selector:
        date:
